### PR TITLE
Compabitility fix with 1.14.4 and latest "fabric-carpet" mod

### PR DESCRIPTION
**Pull request by codesource**

### CODE REVIEW

**Comment by codesource** [comment]
Removed the added elytra recipe from this commit, it's not a bug fix.

**Comment by DeadlyMC** [comment]
We still plan to support quickcarpet, if those black/whitelist files stay they shouldn't cause any issues.
Also i don't get why u had to delete and recreate `initialiseRecipes.json`
The magma_cream recipe change seems sweet

**Comment by codesource** [comment]
Anderstand about the support of quickcarpet, I will test if the datapack load **with** theses rules. I had errors on log, that the reason I deleted them.

**Comment by codesource** [comment]
About the `initializeRecipes.json` there is different issues:
- Json format is not correct (due to typographic quote)
- Minecraft filename format for `advancements` don't accept uppercase 

> [Server-Worker-6/ERROR]: Non [a-z0-9/._-] character in path of location: skyblock:advancements/initialiseRecipes.json

- Rewards has to be an array even if there is only one element

**Comment by codesource** [comment]
Tests are done, the datapack can't be loaded with "black/whitelist".

> [Server thread/ERROR]: Couldn't load block tag carpet:dispenser_placeable_whitelist as it either references another tag that doesn't exist, or ultimately references itself

We could perhaps do a branch specific to "fabric-carpet"?

**Comment by DeadlyMC** [comment]
I think it should be fine with the blacklist and whitelist stuff staying, cause it just puts an error in the log..i believe the rest of the stuff works and i should probs add that support to fabric-carpet mod too

**Comment by codesource** [comment]
I will test it with a fresh install of a server and tell you if the datapack load with the "black/white".

**Comment by codesource** [comment]
OK, tests are done.

I have done a specific branch for this test where I have cherry-pick only the other fixes.
[(test-black-white)](https://github.com/codesource/Skyblock-datapack/tree/test-black-white)

I tested with this:
launcher:
[Fabric server 0.5.1.37](https://fabricmc.net/use/)

server: 
[2019-11-09-01-46-25-minecraft_server.1.14.4.jar](https://www.minecraft.net/en-us/download/server/)

mods:
- [fabric-carpet-1.14.4-1.2.0+v191020.jar](https://github.com/gnembon/fabric-carpet/releases)
- [skyblock-fc-1.14.4-1.0.0.jar](https://github.com/skyrising/skyblock/releases)

server.properties:
`level-type=skyblock`

datapack:
[Skyblock-datapack (branch test-black-white)](https://github.com/codesource/Skyblock-datapack/tree/test-black-white)

And I get this error:

> [12:38:14] [Server thread/ERROR]: Couldn't load block tag carpet:dispenser_placeable_whitelist as it either references another tag that doesn't exist, or ultimately references itself
[12:38:14] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot build unresolved tag entry
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_222]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1473) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:458) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:374) [intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:218) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:615) [intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.IllegalStateException: Cannot build unresolved tag entry
	at net.minecraft.class_3494$class_3497.method_15157(class_3494.java:224) ~[intermediary-server.jar:?]
	at net.minecraft.class_3494.<init>(class_3494.java:38) ~[intermediary-server.jar:?]
	at net.minecraft.class_3494$class_3495.method_15144(class_3494.java:131) ~[intermediary-server.jar:?]
	at net.minecraft.class_3503.method_20733(class_3503.java:136) ~[intermediary-server.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_222]
	at net.minecraft.class_3503.method_18242(class_3503.java:136) ~[intermediary-server.jar:?]
	at net.minecraft.class_3505.method_18245(class_3505.java:68) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_222]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1471) ~[intermediary-server.jar:?]
	... 5 more

**Pull request closed without merging**
