### PR TITLE
Added functionality to spawn the island

### PR DESCRIPTION
**Pull request by tintin10q**
Added function to spawn in the island '/function minecraft:spawn_island'
Added structure file for the island called 'skyblock_platform'
Updated the readme

### CODE REVIEW

**Comment by skyrising** [comment]
Can you change it from `minecraft:` to `skyblock:`?

**Comment by tintin10q** [comment]
I changed it

**Comment by skyrising** [comment]
Thanks

**Comment by tintin10q** [comment]
Are you going to merge them?

**Comment by DeadlyMC** [comment]
Thanks a lot! Really appreciate your help :D

**Pull request merged**
